In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr2d=np.array([[1,2,3,4,5],[2,3,4,1,4]])
arr2d

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 1, 4]])

In [7]:
arr3d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,22]])
arr3d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 22]])

In [8]:
arr3d.shape

(3, 4)

In [9]:
arr3d.ndim

2

In [10]:
arr2d.ndim

2

In [11]:
arr2d.size

10

In [12]:
arr3d.size

12

In [13]:
arr2d.shape

(2, 5)

In [14]:
arr.dtype

dtype('int64')

In [15]:
arr3d.dtype

dtype('int64')

In [16]:
arry=np.array([1,2,3,4,5,6])

In [17]:
arry

array([1, 2, 3, 4, 5, 6])

In [18]:
arry.sum()

np.int64(21)

In [19]:
arry.mean()

np.float64(3.5)

In [23]:
arry.min()

np.int64(1)

In [24]:
arry.max()

np.int64(6)

In [25]:
arry2d=np.array([[1,2,3,4],[5,6,7,8]])

In [26]:
arry2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arry2d.sum()

np.int64(36)

In [28]:
arry2d.mean()

np.float64(4.5)

In [29]:
arry2d.min()

np.int64(1)

In [30]:
arry2d.max()

np.int64(8)

In [31]:
arry2d.sum(axis=0)

array([ 6,  8, 10, 12])

In [32]:
arry2d.sum(axis=1)

array([10, 26])

In [33]:
arry2d.mean(axis=0)

array([3., 4., 5., 6.])

In [34]:
arry2d.mean(axis=1)

array([2.5, 6.5])

In [35]:
arr1=np.array([10,20,30,40,50])
arr1[0]

np.int64(10)

In [36]:
arr1[4]

np.int64(50)

In [37]:
arr1[1:3]

array([20, 30])

In [40]:
arr1[-3:-1]

array([30, 40])

In [42]:
arr12d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [43]:
arr12d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
arr12d[0,3]

np.int64(4)

In [50]:
arr12d[1,3]

np.int64(8)

In [51]:
arr12d[-3,-1]

np.int64(4)

In [53]:
arr12d[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
arr12d[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr12d[0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
arr12d[1,:]

array([5, 6, 7, 8])

In [57]:
arr12d[2:]

array([[ 9, 10, 11, 12]])

In [58]:
arr12d[:,1]

array([ 2,  6, 10])

In [59]:
arr12d[:,3]

array([ 4,  8, 12])

In [64]:
arry=np.array([1,2,3,4,5,7,8])
mark=arry>3
mark

array([False, False, False,  True,  True,  True,  True])

In [65]:
arry[mark]

array([4, 5, 7, 8])

In [67]:
arry[arry % 2==0]

array([2, 4, 8])

In [70]:
arry[arry % 3==0]

array([3])

In [72]:
arr=np.array([1,2,3,4,5])
arr+5

array([ 6,  7,  8,  9, 10])

In [73]:
arr*3

array([ 3,  6,  9, 12, 15])

In [74]:
arr-1

array([0, 1, 2, 3, 4])

In [75]:
arr**2

array([ 1,  4,  9, 16, 25])

In [76]:
arr**3

array([  1,   8,  27,  64, 125])

In [77]:
b=2


In [78]:
arr+b

array([3, 4, 5, 6, 7])

In [81]:
arr1=np.array([1,2,3,2])
arr2=np.array([[1,2,3,4],[2,3,4,5]])

In [82]:
arr1*arr2

array([[ 1,  4,  9,  8],
       [ 2,  6, 12, 10]])

In [83]:
arr1.shape

(4,)

In [84]:
arr2.shape

(2, 4)

In [86]:
arr1+arr2

array([[2, 4, 6, 6],
       [3, 5, 7, 7]])

In [87]:
arr1=np.arange(12)

In [88]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
arr2d=arr1.shape

In [91]:
arr2d

(12,)

In [92]:
arr2d=arr1.reshape(4,3)

In [93]:
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
arr2d.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [95]:
arr2d.shape

(4, 3)

In [97]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [99]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [100]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [101]:
np.linalg.eig(A)  

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [103]:
np.random.seed(42)
rand_arr=np.random.rand(3,3)

In [104]:
rand_arr

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [105]:
rand_int = np.random.randint(0,10,size=(2,5))

In [106]:
rand_int

array([[7, 2, 5, 4, 1],
       [7, 5, 1, 4, 0]], dtype=int32)

✅ Suggested Mini Exercises (Practice)

In [108]:
arr2d=np.array([[1,2,3,4],[5,6,7,8]])

In [109]:
arr2d.sum(axis=0)

array([ 6,  8, 10, 12])

In [110]:
arr2d.sum(axis=1)

array([10, 26])

In [112]:
arr2d[1,:]

array([5, 6, 7, 8])

In [113]:
arr2d[:,1]

array([2, 6])

In [114]:
mask=arr2d>5


In [115]:
arr2d[mask]

array([6, 7, 8])

In [117]:
arr2d[arry2d%2==0]

array([2, 4, 6, 8])

In [118]:
arr2d*5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [119]:
arr2d**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [120]:
arr2d+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [121]:
arr2d.shape

(2, 4)

In [124]:
a=arr2d.reshape(4,2)

In [125]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [126]:
a.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [127]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
a=np.array([[1,2],[8,3],[4,8],[9,0]])
b=np.array([[3,8],[2,0],[3,7],[8,0]])

In [129]:
a*b

array([[ 3, 16],
       [16,  0],
       [12, 56],
       [72,  0]])

In [132]:
a=np.array([[1,2],[8,2]])
b=np.array([[4,8],[9,0]])

c=np.dot(b,a)


In [133]:
c

array([[68, 24],
       [ 9, 18]])

In [134]:
rand_arr=np.random.rand(3,3)

In [137]:
rand_arr

array([[0.30424224, 0.52475643, 0.43194502],
       [0.29122914, 0.61185289, 0.13949386],
       [0.29214465, 0.36636184, 0.45606998]])

In [140]:
rand_arr.mean

<function ndarray.mean>

In [141]:
rand_arr.min

<function ndarray.min>

In [142]:
rand_arr.max

<function ndarray.max>

In [148]:
rand_int=np.random.randint(1,10, size=(3,3))

In [149]:
rand_int

array([[7, 4, 8],
       [5, 7, 3],
       [7, 8, 5]], dtype=int32)

In [146]:
rand_int.mean

<function ndarray.mean>

In [147]:
np.random.seed(42) 